#!/usr/bin/env bash

#### region Constants, utils and error handling

set -euo pipefail
if [[ ${DEBUG:-0} -eq 1 ]]; then
    export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -x
fi

declare -r UNITS_DIR=${1:?}
declare -r MOUNTDIR_PARENT="/media"
# Config files should be imported, first ones step over the others:
#   - /etc/automounts.d
#   - /usr/local/lib/automounts.d
#   - /usr/lib/automounts.d
declare -ar CONF_DIRS=(
    /etc/automounts.d
    /usr/local/lib/automounts.d
    /usr/lib/automounts.d
)

log() {
    local loglevel=${loglevel:-info}
    if [[ ${SYSTEMD_SCOPE:-} =~ ^user$|^system$ ]]; then
        echo "$*" | systemd-cat -p "${loglevel}" -t "media-automount-generator"
    else
        echo >&2 "[${loglevel^^}]: $*"
    fi
}

die() {
    loglevel=err log "$@"
    exit 1
}

_on_err() {
    loglevel=err log "Something went wrong"
    exit 0
}

# Search for the first matching file path in one of the config directories.
# Return an empty string if no matching file was found.
#
# Params:
#   $1 - File name
#
# Returns:
#   Path of the file. Empty string if none found
get_file_from_conf() {
    local file_name=${1:?}
    local result

    for conf_dir in "${CONF_DIRS[@]}"; do
        result=${conf_dir}/${file_name}
        if [[ -r "${result}" ]]; then
            echo "$result"
            return 0
        fi
    done
}

trap '_on_err' ERR

#### endregion

#############################################################

# Dont run if we are in a container or a virtual machine
if [[ -n ${SYSTEMD_VIRTUALIZATION:-} ]]; then
    log "System is running in ${SYSTEMD_VIRTUALIZATION}, skipping..."
    exit 0
fi

# Check if generator is wanted to be enabled.
# WARNING: This only should be used by the system admin and not the vendor.
# WARNING: This file SHOULD NOT contain any configuration.
# It is meant to be a global /dev/null symlink.
global_conf_file=$(get_file_from_conf _all)

# Iterate in a list of partitions
for dev in $(lsblk -n --shell --output PATH --filter 'TYPE == "part"'); do
    # Check if the device is already set for mounting, and if is, skip it
    if findmnt "$dev" &>/dev/null; then
        log "$dev: device is already mounted. Skipping..."
        continue
    fi

    # Check if is removable, and if so, skip it
    parent_dev=$(lsblk -n --inverse --output=NAME --filter='TYPE == "disk"' "$dev" | tail -1)
    if [[ $(</sys/block/"$parent_dev"/removable) -eq 1 ]]; then
        log "$dev: device is removable. Skipping..."
        continue
    fi

    # Check if we have a config for the partition type
    fstype=$(lsblk -n --output FSTYPE "$dev")
    [[ -z $fstype ]] && continue
    conf_file=${global_conf_file:-$(get_file_from_conf "$fstype")}
    if [[ -z $conf_file ]]; then
        log "$dev: Config for filesystem $fstype was not found"
        continue
    elif [[ $(realpath "$conf_file") == /dev/null ]]; then # When the file is a symlink pointing at /dev/null
        log "$dev: Masking conf file $conf_file pointing at /dev/null. Skipping..."
        continue
    fi

    # Load the config file
    unset -v FSOPTIONS
    # shellcheck disable=SC1090
    eval "$(
        source "$conf_file" >/dev/null
        echo "${FSOPTIONS@A}"
    )"

    # Write the unit file
    dev_uuid="$(lsblk -n --output UUID "$dev")"
    What="UUID=$dev_uuid"
    Where=$(realpath -m ${MOUNTDIR_PARENT%%/}/"$dev_uuid") # Get device UUID
    unit_file_path="$UNITS_DIR"/"$(systemd-escape -p --suffix=mount "$Where")"
    cat <<EOF >"$unit_file_path"
[Unit]
SourcePath=${conf_file}
Before=local-fs.target

[Mount]
What=${What:?}
Where=${Where:?}
Type=${fstype:?}
${FSOPTIONS:+Options=${FSOPTIONS}}
EOF
    if [[ ! -s $unit_file_path ]]; then
        log "$dev: Generated mount unit file at $unit_file_path is empty. Skipping..."
        continue
    fi
    log "$dev: Generated mount unit file at $unit_file_path"
    mkdir -p "${UNITS_DIR}"/local-fs.target.wants
    ln -sr "$unit_file_path" "${UNITS_DIR}"/local-fs.target.wants/
    log "$dev: Symlinked $unit_file_path to ${UNITS_DIR}/local-fs.target.wants/$(basename "$unit_file_path")"
done

log "Unit files were generated. Stopping process..."
