name: Continuous Deployment

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    generate-changelog:
        name: Generate changelog
        runs-on: ubuntu-22.04
        outputs:
            release_body: ${{ steps.git-cliff.outputs.content }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Generate a changelog
                uses: orhun/git-cliff-action@main
                id: git-cliff
                with:
                    config: cliff.toml
                    args: -vv --latest -o CHANGELOG.md --no-exec --github-repo ${{ github.repository }}
            -   name: GH Release
                uses: softprops/action-gh-release@v2.2.1
                with:
                    token: '${{ github.token }}'
                    body_path: CHANGELOG.md